# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-state-development-eu-north-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "terraform/eu-north-1/development/apps/terraform.tfstate"
    region         = "eu-north-1"
  }
}
