# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-north-1"
  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["019496914213"]
}
