{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app-php.serviceAccountName" . }}
  labels:
{{ include "app-php.labels" . | indent 4 }}
{{- end -}}
