apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apple
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apple-service
            port:
              number: 5678
